<?php

declare(strict_types=1);

use Axleus\Message\SystemMessage;

$this->headTitle($this->appName)->setSeparator(' - ')->setAutoEscape(false)
?>
<?=$this->headTitle($this->title);?>
<header id="app-header" class="container" style="margin-top:0; padding-top: 0;">
    <nav id="nav">
        <ul>
            <li>
                <a href="<?=$this->url('home')?>">
                    <img src="<?=$this->basePath('front-end/images/axleus-logo.svg')?>" alt="Freelancer by Axleus" width="150" />
                </a>
            </li>
        </ul>
        <ul>
            <li>
                <a href="https://github.com/axleus" target="_blank">
                    <i class="bi-github"></i>
                </a>
            </li>
            <li>
                <a href="https://github.com/axleus/freelancer" target="_blank">
                    <i class="bi-envelope-fill"></i>
                </a>
            </li>
        </ul>
        <?=$this->navigation('Mimmi20\Mezzio\Navigation\Default')->menu()?>
    </nav>
    <?=$this->systemMessage(SystemMessage::SYSTEM_MESSAGE_KEY)?>
</header>